name: Update arXiv Papers

on:
  schedule:
    # Run daily at noon UTC
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-papers:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Generate HTML
      run: python3 generate_arxiv_snapshot.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add arxiv-papers.html
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update arXiv papers" && git push)
